Add code that was commented for testing

diff --git a/desktopify b/desktopify
--- a/desktopify
+++ b/desktopify
@@ -1,24 +1,24 @@
 #!/usr/bin/env bash
 
-# # Check if the user running the script is root
-# if [ $(id -u) -ne 0 ]; then
-#   echo "[!] ERROR: You need to be root."
-#   exit 1
-# fi
+# Check if the user running the script is root
+if [ $(id -u) -ne 0 ]; then
+  echo "[!] ERROR: You need to be root."
+  exit 1
+fi
 
-# # Check if we're running on a Raspberry Pi
-# IS_PI=$(grep Model /proc/cpuinfo | grep Raspberry)
-# if [ $? -ne 0 ]; then
-#   echo "[!] This is not a Raspberry Pi. Quitting!"
-#   exit 1
-# fi
+# Check if we're running on a Raspberry Pi
+IS_PI=$(grep Model /proc/cpuinfo | grep Raspberry)
+if [ $? -ne 0 ]; then
+  echo "[!] This is not a Raspberry Pi. Quitting!"
+  exit 1
+fi
 
-# # Check if we're running Ubuntu
-# IS_UBUNTU=$(lsb_release -is)
-# if [ "${IS_UBUNTU}" != "Ubuntu" ]; then
-#   echo "[!] This script is only intended to run on Ubuntu."
-#   exit 1
-# fi
+# Check if we're running Ubuntu
+IS_UBUNTU=$(lsb_release -is)
+if [ "${IS_UBUNTU}" != "Ubuntu" ]; then
+  echo "[!] This script is only intended to run on Ubuntu."
+  exit 1
+fi
 
 # Display help usage
 function usage () {
