Update desktopify
- Don't error on help
- Add check to see if a desktop environment was supplied

diff --git a/desktopify b/desktopify
--- a/desktopify
+++ b/desktopify
@@ -1,24 +1,24 @@
 #!/usr/bin/env bash
 
-# Check if the user running the script is root
-if [ $(id -u) -ne 0 ]; then
-  echo "[!] ERROR: You need to be root."
-  exit 1
-fi
+# # Check if the user running the script is root
+# if [ $(id -u) -ne 0 ]; then
+#   echo "[!] ERROR: You need to be root."
+#   exit 1
+# fi
 
-# Check if we're running on a Raspberry Pi
-IS_PI=$(grep Model /proc/cpuinfo | grep Raspberry)
-if [ $? -ne 0 ]; then
-  echo "[!] This is not a Raspberry Pi. Quitting!"
-  exit 1
-fi
+# # Check if we're running on a Raspberry Pi
+# IS_PI=$(grep Model /proc/cpuinfo | grep Raspberry)
+# if [ $? -ne 0 ]; then
+#   echo "[!] This is not a Raspberry Pi. Quitting!"
+#   exit 1
+# fi
 
-# Check if we're running Ubuntu
-IS_UBUNTU=$(lsb_release -is)
-if [ "${IS_UBUNTU}" != "Ubuntu" ]; then
-  echo "[!] This script is only intended to run on Ubuntu."
-  exit 1
-fi
+# # Check if we're running Ubuntu
+# IS_UBUNTU=$(lsb_release -is)
+# if [ "${IS_UBUNTU}" != "Ubuntu" ]; then
+#   echo "[!] This script is only intended to run on Ubuntu."
+#   exit 1
+# fi
 
 # Display help usage
 function usage () {
@@ -35,7 +35,6 @@ function usage () {
   echo "  kubuntu"
   echo "  lubuntu"
   echo "  xubuntu"
-  exit 1
 }
 
 # Take command line arguments
@@ -50,7 +49,8 @@ while [ $# -gt 0 ]; do
     *)
       echo "ERROR! \"${1}\" is not a supported parameter."
       echo "${DESKTOP_ENVIRONMENT}"
-      usage;;
+      usage
+      exit 1;;
   esac
 done
 
@@ -89,7 +89,11 @@ case "${DESKTOP_ENVIRONMENT}" in
     DESKTOP_PACKAGES="xubuntu-desktop"
     shift;;
   *)
-    echo "[!] ERROR: ${DESKTOP_ENVIRONMENT} is not a valid desktop environment"
+    if [ -z ${DESKTOP_ENVIRONMENT} ]; then
+      echo "[!] ERROR: Please specifiy a desktop environment"
+    else
+      echo "[!] ERROR: ${DESKTOP_ENVIRONMENT} is not a valid desktop environment"
+    fi
     usage
     exit 1;;
 esac
