Put the check after the option parser
Allows help to be accessed without `sudo` or running on a Pi.

diff --git a/desktopify b/desktopify
--- a/desktopify
+++ b/desktopify
@@ -1,40 +1,5 @@
 #!/usr/bin/env bash
 
-# Check if the user running the script is root
-if [ "$(id -u)" -ne 0 ]; then
-  echo "[!] ERROR: You need to be root."
-  exit 1
-fi
-
-HOST_ARCH=$(uname -m)
-if [ "${HOST_ARCH}" != "armv7l" ] && [ "${HOST_ARCH}" != "aarch64" ]; then
-  echo "[!] This script is only intended to run on ARM devices."
-  exit 1
-fi
-
-# Check if we're running on a Raspberry Pi
-PI_MODEL=$(grep ^Model /proc/cpuinfo  | cut -d':' -f2- | sed 's/ R/R/')
-if [[ "${PI_MODEL}" == *"Raspberry Pi"* ]]; then
-  echo "[+] Configuring your ${PI_MODEL}"
-else
-  echo "[!] This is not a Raspberry Pi. Quitting!"
-  exit 1
-fi
-
-# Check if we're running Ubuntu
-IS_UBUNTU=$(lsb_release -is)
-if [ "${IS_UBUNTU}" != "Ubuntu" ]; then
-  echo "[!] This script is only intended to run on Ubuntu."
-  exit 1
-fi
-
-# Check if we're running 20.04
-CODENAME=$(lsb_release -cs)
-if [ "${CODENAME}" != "focal" ]; then
-  echo "[!] This script is only intended to run on Ubuntu 20.04."
-  exit 1
-fi
-
 # Display help usage
 function usage () {
   echo
@@ -152,6 +117,40 @@ case "${DESKTOP_ENVIRONMENT}" in
     exit 1;;
 esac
 
+# Check if the user running the script is root
+if [ "$(id -u)" -ne 0 ]; then
+  echo "[!] ERROR: You need to be root."
+  exit 1
+fi
+
+HOST_ARCH=$(uname -m)
+if [ "${HOST_ARCH}" != "armv7l" ] && [ "${HOST_ARCH}" != "aarch64" ]; then
+  echo "[!] This script is only intended to run on ARM devices."
+  exit 1
+fi
+
+# Check if we're running on a Raspberry Pi
+PI_MODEL=$(grep ^Model /proc/cpuinfo  | cut -d':' -f2- | sed 's/ R/R/')
+if [[ "${PI_MODEL}" == *"Raspberry Pi"* ]]; then
+  echo "[+] Configuring your ${PI_MODEL}"
+else
+  echo "[!] This is not a Raspberry Pi. Quitting!"
+  exit 1
+fi
+
+# Check if we're running Ubuntu
+IS_UBUNTU=$(lsb_release -is)
+if [ "${IS_UBUNTU}" != "Ubuntu" ]; then
+  echo "[!] This script is only intended to run on Ubuntu."
+  exit 1
+fi
+
+# Check if we're running 20.04
+CODENAME=$(lsb_release -cs)
+if [ "${CODENAME}" != "focal" ]; then
+  echo "[!] This script is only intended to run on Ubuntu 20.04."
+  exit 1
+fi
 
 # Do the installation
 HARDWARE_PACKAGES="pi-bluetooth"
